common/models/AuthItem.php
<?php
/**
 * Created by PhpStorm.
 * User: phpNT - http://phpnt.com
 * Date: 04.07.2016
 * Time: 11:32
 */

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * Роли и допуски
 *
 * @property string $name
 * @property integer $type
 * @property string $description
 * @property string $rule_name
 * @property string $data
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property AuthAssignment[] $authAssignments
 * @property User[] $users
 * @property AuthRule $ruleName
 * @property AuthItemChild[] $authItemChildren
 * @property AuthItemChild[] $authItemChildren0
 * @property AuthItem[] $parents
 * @property AuthItem[] $children
 */
class AuthItem extends \yii\db\ActiveRecord
{
    const TYPE_ROLE = 1;        // Роль
    const TYPE_PERMISSION = 2;  // Допуск

    public $children_array = [];    // Дочерние роли/допуски
    public $user_array = [];        // Пользователи, обаладающие ролью/допуском

    /**
     * Наименование таблицы
     * @return string
     */
    public static function tableName()
    {
        return 'auth_item';
    }

    /**
     * Автозаполнение даты создания и редактирования
     * @return array
     */
    public function behaviors()
    {
        return [[
            'class' => TimestampBehavior::className(),
            'createdAtAttribute' => 'created_at',
            'updatedAtAttribute' => 'updated_at',
            'value' => time(),
        ]];
    }

    /**
     * Типы записей (роль или допуск)
     * @return array
     */
    public static function getTypes()
    {
        return [
            '1' => Yii::t('app', 'Роль'),
            '2' =>  Yii::t('app', 'Допуск')
        ];
    }

    /**
     * Правила валидации
     * @return array
     */
    public function rules()
    {
        return [
            [['name', 'type', 'description'], 'required'],  // Обязательны для заполнения
            ['name', 'match', 'pattern' => '/^[a-zA-Z0-9_-]+$/','message' => Yii::t('app', 'Допустимы только латинские буквы и цифры.')], // Латинские буквы и цифры
            [['name', 'description'], 'unique'],    // Уникальные значения
            [['type', 'created_at', 'updated_at'], 'integer'],  // Целочисленные значения
            [['description', 'data'], 'string'],    // Строковые значения
            [['name', 'rule_name'], 'string', 'max' => 64], // Строковые значения (максимум 64 символов)
            [['rule_name'], 'exist', 'skipOnError' => true, 'targetClass' => AuthRule::className(), 'targetAttribute' => ['rule_name' => 'name']],
            [['children_array', 'user_array'], 'safe'], // Безопасные аттрибуты
            [['name', 'description'], 'filter', 'filter' => 'trim'],    // Обрезаем строки по краям
            [['description', 'rule_name', 'data',
                'created_at', 'updated_at'], 'default', 'value' => null],   // По умолучанию = null
            ['type', 'default', 'value' => self::TYPE_ROLE], // По умолчанию тип записи "Роль"
        ];
    }

    /**
     * Наименование полей аттрибутов
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('app', 'Название'),
            'type' => Yii::t('app', 'Тип'),
            'description' => Yii::t('app', 'Описание'),
            'rule_name' => Yii::t('app', 'Правило'),
            'data' => Yii::t('app', 'Данные'),
            'created_at' => Yii::t('app', 'Создана'),
            'updated_at' => Yii::t('app', 'Редактирована'),
            'children_array' =>  Yii::t('app', 'Обладает допусками'),
            'user_array' => Yii::t('app', 'Пользователи имеют'),
        ];
    }

    /**
     * Связь название роли => пользователь
     * @return \yii\db\ActiveQuery
     */
    public function getAuthAssignments()
    {
        return $this->hasMany(AuthAssignment::className(), ['item_name' => 'name']);
    }

    /**
     * Пользователи, обладающие текущей ролью или допуском
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->viaTable('auth_assignment', ['item_name' => 'name']);
    }

    /**
     * Правило, которому принадлежит допуск
     * @return \yii\db\ActiveQuery
     */
    public function getRuleName()
    {
        return $this->hasOne(AuthRule::className(), ['name' => 'rule_name']);
    }

    /**
     * Дочерние роли или допуски по связи child
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemChildren()
    {
        return $this->hasMany(AuthItemChild::className(), ['child' => 'name']);
    }

    /**
     * Дочерние роли или допуски по связи parent
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemChildren0()
    {
        return $this->hasMany(AuthItemChild::className(), ['parent' => 'name']);
    }

    /**
     * Родительские роли или допуски
     * @return \yii\db\ActiveQuery
     */
    public function getParents()
    {
        return $this->hasMany(AuthItem::className(), ['name' => 'parent'])->viaTable('auth_item_child', ['child' => 'name']);
    }

    /**
     * Дочерние роли или допуски
     * @return \yii\db\ActiveQuery
     */
    public function getChildren()
    {
        return $this->hasMany(AuthItem::className(), ['name' => 'child'])->viaTable('lb_auth_item_child', ['parent' => 'name']);
    }

    /**
     * Заполнение массива дочерних ролей и допусков
     * Заполнение массива пользователей, обладающих ролью или допуском
     *
     * Выполняется, как правило, при инциализации модели
     */
    public function fill()
    {
        // Дочерние роли и допуски
        if ($this->children) {
            foreach ($this->children as $child) {
                $this->children_array[$child->name] = $child->description;
            }
        }
        // Пользователи
        if ($this->users) {
            foreach ($this->users as $user) {
                $name = ($user->last_name) ? $user->first_name ." ".$user->last_name : $user->first_name;
                $name .= " (" . $user->id . ")"; // добавляем ID к надписи
                $this->user_array[$user->id] = $name;
            }
        }
    }

    /**
     * Список всех допусков и ролей массивом
     * @param array $type - тип записи (1 - роль, 2 - допуск) по умолчанию оба
     * @return array
     */
    public static function getAll($type = [1,2])
    {
        $auths = [];
        $model = self::find()
            ->where(['type' => $type])
            ->all();
        if ($model) {
            foreach ($model as $m) {
                $auths[$m->name] = $m->description;
            }
        }
        return $auths;
    }

    /**
     * Записываем роли, допуски и их связи в
     * соотествующие таблицы после сохранения
     *
     * @param bool $insert
     * @param array $changedAttributes
     * @return bool
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        // Удаляем сначала прошлые связи с другими ролями и допусками
        AuthItemChild::deleteAll(['parent' => $this->name]);
        // Сохраняем новые связи
        if ($this->children_array) {
            foreach ($this->children_array as $child) {
                $authItemChild = new AuthItemChild();
                $authItemChild->parent = $this->name;
                $authItemChild->child = $child;
                $authItemChild->save();
            }
        }
        // Удаляем сначала прошлые связи с пользователями
        AuthAssignment::deleteAll(['item_name' => $this->name]);
        // Сохраняем новые связи
        if ($this->user_array) {
            foreach ($this->user_array as $user) {
                $authAssignment = new AuthAssignment();
                $authAssignment->item_name = $this->name;
                $authAssignment->user_id = $user;
                $authAssignment->save();
            }
        }

        return true;
    }

    public static function getCompanyRoles()
    {
        return static::find()
            ->where(['type' => self::TYPE_ROLE])
            ->andWhere(['!=', 'name', 'creator'])
            ->andWhere(['!=', 'name', 'admin'])
            ->andWhere(['!=', 'name', 'redactor'])
            ->andWhere(['!=', 'name', 'user'])
            ->orderBy('description')
            ->all();
    }

    /**
     * Return roles.
     * NOTE: used for updating user role (user/update).
     *
     * @return array|\yii\db\ActiveRecord[]
     */
    public static function getRoles()
    {
        // we make sure that only You can see theCreator role in drop down list
        if (\Yii::$app->user->can('Создатель'))
        {
            return static::find()->select('name')->where(['type' => 1])->all();
        }
        // admin can not see theCreator role in drop down list
        else
        {
            return static::find()
                ->where(['type' => self::TYPE_ROLE])
                ->andWhere(['!=', 'name', 'creator'])
                ->orderBy('description')
                ->all();
        }
    }

    public static function getUserRoles()
    {
        return static::find()
            ->where(['type' => self::TYPE_ROLE])
            ->andWhere(['!=', 'name', 'creator'])
            ->andWhere(['!=', 'name', 'userCompany'])
            ->andWhere(['!=', 'name', 'adminCompany'])
            ->andWhere(['!=', 'name', 'managerCompany'])
            ->orderBy('description')
            ->all();
    }

    public static function getUserTariffes()
    {
        return static::find()
            ->where(['type' => self::TYPE_PERMISSION])
            ->andWhere(['!=', 'name', 'corporate'])
            ->andWhere(['!=', 'name', 'authorRule'])
            ->andWhere(['!=', 'name', 'manageCompany'])
            ->orderBy('description')
            ->all();
    }

    public static function getTariffes()
    {
        return static::find()
            ->where(['type' => self::TYPE_PERMISSION])

frontend/views/questionary/_agency.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\questionary\agency */
/* @var $form ActiveForm */

?>
<div class="questionary-_agency">
    <h3>Анкета для агенства</h3>

        <?= $form->field($model, 'adress')->textInput() ?>
        <?= $form->field($model, 'name')->textInput() ?>
        <?= $form->field($model, 'age')->textInput() ?>
<!--        --><?//= $form->field($model, 'model_category')->checkboxList($model->model_category) ?>
        <?= $form->field($model, 'professional_experience') ?>
        <?= $form->field($model, 'total_models') ?>
        <?= $form->field($model, 'specialization') ?>
        <?= $form->field($model, 'other_requipments') ?>
        <?= $form->field($model, 'social_media') ?>
        <?= $form->field($model, 'main_reason_on_site') ?>

</div><!-- questionary-_agency -->

frontend/views/questionary/_brand.php
<?php

use yii\widgets\ActiveForm;
?>

<?= $form->field($model, 'company_name') ?>
<?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences) ?>
<?= $form->field($model, 'product_range')->checkboxList($model->productRanges) ?>
<?= $form->field($model, 'trading')->dropDownList($model->tradingList) ?>

frontend/views/questionary/_buyer.php
<?php

use yii\widgets\ActiveForm;
?>

<?= $form->field($model, 'clients_work')->textarea() ?>
<?= $form->field($model, 'brands_work')->textarea() ?>
<?= $form->field($model, 'product_range')->checkboxList($model->productRanges) ?>
<?= $form->field($model, 'trading')->dropDownList($model->tradingList) ?>
<?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences) ?>

frontend/views/questionary/_designer.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\questionary\forms\DesignerForm */
/* @var $form ActiveForm */
?>
<div class="questionary-_designer">

        <?= $form->field($model, 'work_type')->checkboxList($model->types) ?>
        <?= $form->field($model, 'workplace')->textarea() ?>
        <?= $form->field($model, 'education')->textarea() ?>
        <?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences) ?>
        <?= $form->field($model, 'compensation')->checkboxList($model->compensations) ?>

</div><!-- questionary-_designer -->

frontend/views/questionary/_fashion_expert.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $form ActiveForm */
/* @var $professions_expert common\models\questionary\expert\ */
$this->registerJSFile('@web/js/questionary/expert.js', ['depends' => 'yii\web\JqueryAsset']);

?>
<?php
Pjax::begin([
    'id' => 'pjaxBlock',
    'enablePushState' => false,
]);
?>

    <?= $form->field($model, 'specialization')->checkboxList($model->specializationList,
        [
            'onchange' => '
                    $.pjax({
                        type: "POST",
                        url: "'.Url::to(['/site/questionary']).'",
                        data: jQuery("#w0").serialize(),
                        container: "#pjaxBlock",
                        push: false,
                        scrollTo: false
                    });
                    ',
        ])
        ->hint(Yii::t('app', 'укажите Вашу специализацию')) ?>

    <?php foreach ($professions_expert as $profession) : ?>
        <h3><?= $profession->title ?></h3>
        <?= $this->render('../questionary/_experts/'.$profession->view , [
            'form'	 => $form,
            'model' => $profession
        ]) ?>
    <?php endforeach ?>
    <?php Pjax::end(); ?>

frontend/views/questionary/_general.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use phpnt\bootstrapSelect\BootstrapSelectAsset;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\questionary\General */
/* @var $form ActiveForm */
BootstrapSelectAsset::register($this);
$this->registerJSFile('@web/js/questionary/general.js', ['depends' => 'yii\web\JqueryAsset']);
?>
<div class="questionary-_general">

        <?= $form->field($general, 'first_name')->textInput() ?>
        <?= $form->field($general, 'last_name')->textInput() ?>

<!--        --><?=$form->field($general->user, 'full_phone', ['template' => '{label}<div class="input-group"><span class="input-group-addon">+</span><div class="text-left" slyle="background-color: #cc0000;">{input}</div></div>']) ?>


<!--        --><?= $form->field($general->user, 'email')->textInput() ?>
        <?= $form->field($general, 'skype')->textInput() ?>
        <?= $form->field($general, 'gender')->dropDownList($general->genders) ?>

        <?php if ($models) echo $form->field($models, 'agency_info')->textArea() ?>
        <?= $form->field($general, 'web_site')->textInput() ?>
        <?= $form->field($general, 'date_of_birth')->widget(DatePicker::classname(), [
            'dateFormat' => 'yyyy-MM-dd',
         ]) ?>

        <?= $form->field($general, 'what_show')->radioList($general->whatShows, [
            'item' => function ($index, $label, $name, $checked, $value) {
                $check = $checked ? ' checked="checked"' : '';
                return "<label class=\"custom-radio\"><input type=\"radio\" name=\"$name\" value=\"$value\"$check><span><div></div></span> $label</label>";
            }
        ]) ?>
        <?php if ($models) echo  $form->field($models, 'legal_agree', [
                'options' => [
                    'id' => 'legal_agree',
                    'style' => 'display:none']
                ])->radioList($models->legalList)?>
    <div class="form-group">
        <label class="control-label" for="location">Локации</label>
        <div class="details-data general-input">
            <?php foreach ($general->locsList as $country => $city_list) : ?>
               <label class="q-check"><input type="checkbox" name="" id = '<?= $country ?>' onchange = 'showOrHide("#<?= $country ?>", "#<?= $country ?>-city");'/><span><div></div></span><?= $country ?>:</label>
                <br>
                <?= $form->field($general, $country, [
                    'options' => [
                        'style' => 'display:none',
                        'id' => $country."-city"
                    ],
                ])->checkboxList($city_list, [
                    'item' => function ($index, $label, $name, $checked, $value) {
                        $check = $checked ? ' checked="checked"' : '';
                        return "<label class=\"custom-radio q-check\"><input type=\"checkbox\" name=\"$name\" value=\"$value\"$check><span><div></div></span>$label</label>";
                    }
                ])->label(false)
                    ?>
                <div class="clearfix"></div>

            <?php endforeach; ?>
        </div>
    </div>


    <?= $form->field($general, 'languages')->checkBoxList($general->langList, [
        'item' => function ($index, $label, $name, $checked, $value) {
            $check = $checked ? ' checked="checked"' : '';
            return "<label class=\"custom-radio\"><input type=\"checkbox\" name=\"$name\" value=\"$value\"$check><span><div></div></span> $label</label>";
        }
    ]) ?>

</div><!-- questionary-_general -->

frontend/views/questionary/_media.php
<?= $form->field($model, 'name') ?>
<?= $form->field($model, 'position')->dropDownList($model->positions) ?>
<?= $form->field($model, 'position_input') ?>
<?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences) ?>

frontend/views/questionary/_models.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form ActiveForm */

$this->registerJSFile('@web/js/questionary/models.js', ['depends' => 'yii\web\JqueryAsset']);

?>
<div class="questionary-_models">
        <?= $form->field($model, 'age')->hiddenInput(['id' => 'age_input'])->label(false) ?>
<!--   Пока не работает     --><?//= $form->field($model, 'metrical')->radioList($model->metricSys) ?>
        <?= $form->field($model, 'height') ?>
        <?= $form->field($model, 'weight') ?>
        <?= $form->field($model, 'waist') ?>
        <?= $form->field($model, 'hips') ?>
        <?= $form->field($model, 'chest') ?>
        <?= $form->field($model, 'dress') ?>
        <?= $form->field($model, 'shoe') ?>
        <?= $form->field($model, 'cup', [
            'options' => [
                'id' => 'cup',
                ]
        ])->dropDownList($model->cups) ?>
        <?= $form->field($model, 'gender')->hiddenInput([
                'id' => 'gender_model'
        ])->label(false) ?>

        <?= $form->field($model, 'ethnicity')->dropDownList($model->ethnicityList) ?>

        <?= $form->field($model, 'ethnicity_input', [
                'options' => [
                    'style' => 'display:none',
                    'id' => 'ethnicity_input'
                ]
        ])->textInput() ?>

        <?= $form->field($model, 'skin_color')->dropDownList($model->skins)->hint(Yii::t('app', 'Укажите цвет Вашей кожи')) ?>
        <?= $form->field($model, 'eye_color')->dropDownList($model->eyes)->hint(Yii::t('app', 'Укажите цвет Ваших глаз')) ?>
        <?= $form->field($model, 'natural_hair_color')->dropDownList($model->hairs)->hint(Yii::t('app', 'Укажите естественный цвет Ваших волос')) ?>
        <?= $form->field($model, 'hair_coloration')->dropDownList($model->hairColorations)->hint(Yii::t('app', 'У Вас окрашены волосы? В какой цвет?')) ?>
        <?= $form->field($model, 'readness_to_change_color')->dropDownList($model->readnessList)->hint(Yii::t('app', 'Готовы ли Вы сменить цвет волос, если это потребуется для работы?')) ?>
        <?= $form->field($model, 'hair_lenght')->dropDownList($model->hairLenghts)->hint(Yii::t('app', 'Какой длинны Ваши волосы')) ?>
        <?= $form->field($model, 'has_tatoo', [
            'options' => ['id' => 'has_tatoos'],
                'inputOptions' => ['class' => 'custom-radio']
        ])->radioList($model->hasTatoos)->hint(Yii::t('app', 'Имеются ли на Вашем теле татуировки?')) ?>
        <?= $form->field($model, 'tatoos',[
            'options' => [
                'style' => 'display:none',
                'id' => 'tatoos'
            ]
        ])->checkBoxList($model->tatoo) ?>
        <?= $form->field($model, 'has_piercing', [
            'options' => ['id' => 'has_piercing']
        ])->radioList($model->hasPiercing)->hint(Yii::t('app', 'Укажите имеется ли у Вас пирсинг не считая сережек в ушах?')) ?>
        <?= $form->field($model, 'piercing', [
            'options' => [
                'style' => 'display:none',
                'id' => 'piercing'
            ]
        ])->checkBoxList($model->piercings) ?>


        <h3>Профессиональные детали</h3>
        <?= $form->field($model, 'model_category')->checkBoxList($model->categories)->hint(Yii::t('app', 'Укажите категории в которых вы работали')) ?>
        <?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences)->hint(Yii::t('app', 'Укажите Ваш опыт работы в данной сфере')) ?>
        <?= $form->field($model, 'additional_skills')->checkBoxList($model->additionalSkills)->hint(Yii::t('app', 'Укажите какими дополнительными навыками Вы владеете')) ?>
        <?= $form->field($model, 'compensation')->checkBoxList($model->compensations)->hint(Yii::t('app', 'Какой вид компенсации Вы хотите получать за свою работы?')) ?>

        <p class="formSubHead">Rates for photoshoot</p>
        <?= $form->field($model, 'rates_for_photoshoot_hour')->hint(Yii::t('app', 'Укажите стоимость одного часа Вашей работы')) ?>
        <?= $form->field($model, 'rates_for_photoshoot_half')->hint(Yii::t('app', 'Сколько будет стоить Ваша работа, если придется работать половину дня (4 часа)')) ?>
        <?= $form->field($model, 'rates_for_photoshoot_full')->hint(Yii::t('app', 'Стоимость Вашей работы за полный день (8 часов)')) ?>
        <?= $form->field($model, 'rates_for_runway')->textarea()->hint(Yii::t('app', 'На какую сумму Вы рассчитываете за выход на подиум?')) ?>




</div><!-- questionary-_models -->

frontend/views/questionary/_photographer.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\questionary\forms\PhotographerForm */
/* @var $form ActiveForm */
?>
<div class="questionary-_photographer">

        <?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences)->hint(Yii::t('app', 'Укажите Ваш опыт работы в данной сфере')) ?>
        <?= $form->field($model, 'work_areas')->checkBoxList($model->areas)->hint(Yii::t('app', 'Уажите в какой специализации Вы работаете')) ?>
        <?= $form->field($model, 'work_type')->checkBoxList($model->types)->hint(Yii::t('app', 'Укажите тип Вашей работы')) ?>
        <?= $form->field($model, 'equipment')->textarea()->hint(Yii::t('app', 'Укажите какой тип оборудования у Вас имеется')) ?>
        <?= $form->field($model, 'studio')->dropDownList($model->provides)->hint(Yii::t('app', 'Имеется ли у Вас своя студия?')) ?>
        <?= $form->field($model, 'makeup_artist')->dropDownList($model->provides)->hint(Yii::t('app', 'Имеется ли у Вас визажист?')) ?>
        <?= $form->field($model, 'hair_stylist')->dropDownList($model->provides)->hint(Yii::t('app', 'Имеется ли у Вас стилист?')) ?>
        <?= $form->field($model, 'compensation')->checkBoxList($model->compensations)->hint(Yii::t('app', 'Какой вид компенсации Вы хотите получать за свою работы?')) ?>
        <?= $form->field($model, 'rates_for_photoshoot_hour')->hint(Yii::t('app', 'Укажите стоимость одного часа Вашей работы')) ?>
        <?= $form->field($model, 'rates_for_photoshoot_half')->hint(Yii::t('app', 'Сколько будет стоить Ваша работа, если придется работать половину дня (4 часа)')) ?>
        <?= $form->field($model, 'rates_for_photoshoot_full')->hint(Yii::t('app', 'Стоимость Вашей работы за полный день (8 часов)')) ?>


</div><!-- questionary-_photographer -->

frontend/views/questionary/_pr.php
<?= $form->field($model, 'workplace') ?>
<?= $form->field($model, 'scope_of_activity') ?>
<?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences) ?>

frontend/views/questionary/_representative.php
<?php

use yii\widgets\ActiveForm;
?>

<?= $form->field($model, 'position')->dropDownList($model->positions)->hint(Yii::t('app', 'Укажите занимаемую должность')) ?>
<?= $form->field($model, 'scope_of_activity')->textarea()->hint(Yii::t('app', 'Опишите чем занимается Ваша компания')) ?>
<?= $form->field($model, 'workplace')->textarea()->hint(Yii::t('app', 'Рабочее место')) ?>
<?= $form->field($model, 'professional_experience')->dropDownList($model->professionalExperiences)->hint(Yii::t('app', 'Укажите Ваш опыт работы в данной сфере')) ?>