common/models/Journal.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "journal".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $photo_id
 * @property integer $category
 * @property integer $author_id
 * @property integer $redactor_id
 * @property integer $content_id
 * @property integer $title_id
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property User $author
 * @property Content $content0
 * @property Photo $photo
 * @property User $redactor
 * @property Content $title0
 */
class Journal extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'journal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content', 'author_id', 'redactor_id', 'created_at', 'updated_at'], 'required'],
            [['content'], 'string'],
            [['photo_id', 'category', 'author_id', 'redactor_id', 'content_id', 'title_id', 'status', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['content_id'], 'unique'],
            [['title_id'], 'unique'],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['author_id' => 'id']],
            [['content_id'], 'exist', 'skipOnError' => true, 'targetClass' => Content::className(), 'targetAttribute' => ['content_id' => 'id']],
            [['photo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Photo::className(), 'targetAttribute' => ['photo_id' => 'id']],
            [['redactor_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['redactor_id' => 'id']],
            [['title_id'], 'exist', 'skipOnError' => true, 'targetClass' => Content::className(), 'targetAttribute' => ['title_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID статьи'),
            'title' => Yii::t('app', 'Название статьи'),
            'content' => Yii::t('app', 'Текст статьи'),
            'photo_id' => Yii::t('app', 'ID картинки, выводимой в списке'),
            'category' => Yii::t('app', 'Категория статьи'),
            'author_id' => Yii::t('app', 'ID автора'),
            'redactor_id' => Yii::t('app', 'ID редактора'),
            'content_id' => Yii::t('app', 'ID контента (для перевода)'),
            'title_id' => Yii::t('app', 'ID названия (для перевода)'),
            'status' => Yii::t('app', 'Статус (публиковать?)'),
            'created_at' => Yii::t('app', 'Создано'),
            'updated_at' => Yii::t('app', 'Обновлено'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent0()
    {
        return $this->hasOne(Content::className(), ['id' => 'content_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhoto()
    {
        return $this->hasOne(Photo::className(), ['id' => 'photo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRedactor()
    {
        return $this->hasOne(User::className(), ['id' => 'redactor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTitle0()
    {
        return $this->hasOne(Content::className(), ['id' => 'title_id']);
    }
}

frontend/controllers/JournalController.php
<?php
namespace frontend\controllers;

use common\models\search\JournalSearch;

use Yii;


class JournalController extends BehaviorsController
{

    public function actionIndex()
    {
        return $this->redirect('category');
    }

    public function actionCategory($category = 'fgnews')
    {
        $contents = JournalSearch::getContent($category);
        return $this->render('index', [
            'contents' => $contents,
            'article' => NULL,
            'category' => $category
            ]);
    }

    public function actionArticle($id)
    {
        $article = JournalSearch::FindOne($id);
        if ($article->status != JournalSearch::STATUS_PUBLIC) {
            unset($article->content);
            $article->title = Yii::t('app', 'Запрашиваемая статья пока не опубликована');
        }
        return $this->render('index', [
            'contents' => NULL,
            'article' => $article,
            'category' => $article->getCategoryById()
            ]);
    }



}

frontend/views/journal/_navbar.php
<?php
use yii\helpers\Url;
?>
<!-- Навигация для журнала -->
<div class="nav-bar">
    <ul class="nav2">
        <li <?php if ($active == 'fgnews') echo 'class="active"'?>>
            <a href="<?= Url::to(['/journal/category', 'category' => 'fgnews'])?>">FG News</a>
        </li>
        <li <?php if ($active == 'fashionshows') echo 'class="active"'?>>
            <a href="<?= Url::to(['/journal/category', 'category' => 'fashionshows'])?>">Fashion Shows</a>
        </li>
        <li <?php if ($active == 'persons') echo 'class="active"'?>>
            <a href="<?= Url::to(['/journal/category', 'category' => 'persons'])?>">Persons</a>
        </li>
        <li <?php if ($active == 'fashionlife') echo 'class="active"'?>>
            <a href="<?= Url::to(['/journal/category', 'category' => 'fashionlife'])?>">Fashion life</a>
        </li>
        <li <?php if ($active == 'blog') echo 'class="active"'?>>
            <a href="<?= Url::to(['/journal/category', 'category' => 'blog'])?>">Blog</a>
        </li>
    </ul>
</div>

frontend/views/journal/index.php
<?php
use yii\helpers\StringHelper;
use yii\helpers\Url;

?>
<?= $this->render('../site/_visitor_nav') ?>
<?php $this->title = 'Fashion Greatness | ' . Yii::t('app', 'Журнал'); ?>

<div class="person-wrapper">
	<div class="j-main">
		<h2>Journal</h2>
		<span class="hr"></span>
			<?= $this->render('_navbar', ['active' => $category]) ?>
			<?php if ($contents): ?>
				<?php foreach ($contents as $content): ?>
				<div class="j-item journal_item">
					<div class="j-img">
						<img src="">
					</div>
					<div class="j-txt">
						<h3><a href="<?= Url::to(['/journal/article/', 'id' => $content->id]) ?>"><?= $content->title ?></a></h3>
						<p><?= StringHelper::truncate($content->content, 250, '...', NULL, TRUE) ?></p>
						<br>
						<p><?= gmdate("Y-m-d H:i", $content->updated_at) ?></p>
					</div>
				</div>
				<?php endforeach ?>
			<?php endif ?>
			<?php if ($article): ?>
				<br>
				<h3><?= $article->title ?></h3>
				<span class="hr"></span>
				<?= $article->content ?>
			<?php endif ?>

	</div>
	<div class="j-sidebar">
		<div class="j-t-port journal_profile">
			<div class="j-t-head">
				Top profile
			</div>
			<div class="j-port-cont">
				<a href="">
					<img src="">
				</a>
			</div>
		</div>
		<div class="j-t-phot journal_photo">
			<div class="j-t-head">
				Top photo
			</div>
			<div class="j-phot-cont">
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
				<a href="">
					<img src="">
				</a>
			</div>
		</div>
	</div>
</div>